name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: lecture.tex
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode --shell-escape
          extra_system_packages: python3-pygments
      - uses: actions/upload-artifact@v2
        with:
          name: output-pdf
          path: lecture.pdf
